package ca.jrvs.apps.trading.service;

import ca.jrvs.apps.trading.data.entity.Account;
import ca.jrvs.apps.trading.data.entity.Trader;
import ca.jrvs.apps.trading.data.entity.TraderAccountView;
import ca.jrvs.apps.trading.data.repository.AccountJpaRepository;
import ca.jrvs.apps.trading.data.repository.PositionRepository;
import ca.jrvs.apps.trading.data.repository.SecurityOrderJpaRepository;
import ca.jrvs.apps.trading.data.repository.TraderJpaRepository;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class TraderAccountService {

  private static final Logger logger = LoggerFactory.getLogger(QuoteService.class);
  private static final String exceptionFormat = "exception in %s, message %s";

  @Autowired
  private TraderJpaRepository traderRepo;

  @Autowired
  private AccountJpaRepository accountRepo;

  @Autowired
  private PositionRepository positionRepo;

  @Autowired
  private AccountService accountService;

  @Autowired
  private SecurityOrderJpaRepository securityOrderRepo;

  /**
   * Create a new trader and initialize a new account with 0 amount - validate user input (all
   * fields must be non empty) - create a trader - create an account - create, setup, and return a
   * new traderAccountView
   * <p>
   * Assumption: to simplify the logic, each trader has only one account where traderId ==
   * accountId
   *
   * @param trader cannot be null. All fields cannot be null except for id (auto-generated by db)
   * @return traderAccountView
   * @throws IllegalArgumentException if a trader has null fields or id is not null
   */
  public TraderAccountView createTraderAndAccount(Trader trader) {
    /*
    if (trader.getId() != 0){
      throw new IllegalArgumentException("Trader id must be 0");
    }
    */
    if (trader != null) {
      final Trader sanitizedTrader = trader;
      Arrays.stream(trader.getClass().getDeclaredFields()).forEach(field -> {
        field.setAccessible(true);
        try {
          if (field.getName() == "id") {
            if (field.getInt(sanitizedTrader) != 0) {
              throw new IllegalArgumentException("Trader id must be 0");
            }
          } else if (field.get(sanitizedTrader) == null) {
            throw new IllegalArgumentException("trader field is null");
          }
        } catch (IllegalAccessException e) {
          handleException("createTraderAndAcount.traderSanitize", e, logger);
        }
      });
    } else {
      throw new IllegalArgumentException("Trader cannot be null");
    }
    trader = traderRepo.save(trader);
    Account account = new Account();
    account.setTraderId(trader.getId());
    account.setAmount(0.0);
    accountRepo.save(account);

    return new TraderAccountView(account, trader);
  }

  /**
   * A trader can be deleted if and only if it has no open position and 0 cash balance - validate
   * traderId - get trader account by traderId and check account balance - get positions by
   * accountId and check positions - delete all securityOrders, account, trader (in this order)
   *
   * @param traderId must not be null
   * @throws IllegalArgumentException if traderId is null or not found or unable to delete
   */
  public void deleteTraderById(Integer traderId) {
    if (traderId == null) {
      throw new IllegalArgumentException("trader id cannot be null");
    }
    if (!traderRepo.existsById(traderId)) {
      throw new IllegalArgumentException("Trader does not exist");
    }
    Account account = accountRepo.getAccountByTraderId(traderId);
    if (account.getAmount() > 0.0) {
      throw new IllegalArgumentException("Trader account amount must be 0.0");
    }
    if (positionRepo.countAllByIdAccountId(account.getId()) > 0) {
      throw new IllegalArgumentException("Trader has positions");
    }
    try {
      securityOrderRepo.deleteAllByAccountId(account.getId());
      accountRepo.delete(account);
      traderRepo.deleteById(traderId);
    } catch (Exception e) {
      throw new IllegalArgumentException("Unable to delete trader");
    }

  }

  /**
   * Deposit a fund to an account by traderId - validate user input - find account by trader id -
   * update the amount accordingly
   *
   * @param traderId must not be null
   * @param fund     must be greater than 0
   * @return updated Account
   * @throws IllegalArgumentException if traderId is null or not found, and fund is less than or
   *                                  equal to 0
   */
  public Account deposit(Integer traderId, Double fund) {
    if (traderId == null || traderId == 0 || fund <= 0.0) {
      throw new IllegalArgumentException("tradedId must be non-null and fun must be positive");
    }
    if (!traderRepo.existsById(traderId)) {
      throw new IllegalArgumentException("Trader does not exist");
    }
    Account account = accountRepo.getAccountByTraderId(traderId);
    if (account == null) {
      throw new IllegalArgumentException("Trader account does not exist");
    }
    account.setAmount(account.getAmount() + fund);
    account = accountRepo.save(account);

    return account;
  }

  /**
   * Withdraw a fund to an account by traderId - validate user input - find account by trader id -
   * update the amount accordingly
   *
   * @param traderId must not be null
   * @param fund     must be greater than 0
   * @return updated Account
   * @throws IllegalArgumentException if traderId is null or not found, and fund is less than or
   *                                  equal to 0
   */
  public Account withdraw(Integer traderId, Double fund) {
    if (traderId == null || traderId == 0 || fund <= 0.0) {
      throw new IllegalArgumentException("tradedId must be non-null and fun must be positive");
    }
    if (!traderRepo.existsById(traderId)) {
      throw new IllegalArgumentException("Trader does not exist");
    }
    Account account = accountRepo.getAccountByTraderId(traderId);
    if (account == null) {
      throw new IllegalArgumentException("Trader account does not exist");
    }
    double withdrawn = account.getAmount() - fund;
    if (withdrawn < 0) {
      withdrawn = 0.0;
    }
    account.setAmount(withdrawn);
    account = accountRepo.save(account);

    return account;
  }

  public static void handleException(String method, Exception e, Logger log) {
    log.warn(String.format(exceptionFormat, method, e.getMessage()));
  }
}
